const MoviesData = [
  {
    id: 1,
    title: "The Shawshank Redemption",
    year: 1994,
    genre: ["Drama"],
    director: "Frank Darabont",
    rating: 9.3,
    actors: ["Tim Robbins", "Morgan Freeman", "Bob Gunton"],
    duration: "2h 22m",
    img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRkb4atRGTrdWBZe798OK0TKPwKt2XhInvthg&s',
  },
  {
    id: 2,
    title: "The Godfather",
    year: 1972,
    genre: ["Crime", "Drama"],
    director: "Francis Ford Coppola",
    rating: 9.2,
    actors: ["Marlon Brando", "Al Pacino", "James Caan"],
    duration: "2h 55m",
    img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRkb4atRGTrdWBZe798OK0TKPwKt2XhInvthg&s'
  },
  {
    id: 3,
    title: "The Dark Knight",
    year: 2008,
    genre: ["Action", "Crime", "Drama"],
    director: "Christopher Nolan",
    rating: 9.0,
    actors: ["Christian Bale", "Heath Ledger", "Aaron Eckhart"],
    duration: "2h 32m",
    img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRkb4atRGTrdWBZe798OK0TKPwKt2XhInvthg&s'
  },
  {
    id: 4,
    title: "Pulp Fiction",
    year: 1994,
    genre: ["Crime", "Drama"],
    director: "Quentin Tarantino",
    rating: 8.9,
    actors: ["John Travolta", "Uma Thurman", "Samuel L. Jackson"],
    duration: "2h 34m",
  },
  {
    id: 5,
    title: "Forrest Gump",
    year: 1994,
    genre: ["Drama", "Romance"],
    director: "Robert Zemeckis",
    rating: 8.8,
    actors: ["Tom Hanks", "Robin Wright", "Gary Sinise"],
    duration: "2h 22m",
  },
  {
    id: 6,
    title: "Inception",
    year: 2010,
    genre: ["Action", "Adventure", "Sci-Fi"],
    director: "Christopher Nolan",
    rating: 8.8,
    actors: ["Leonardo DiCaprio", "Joseph Gordon-Levitt", "Elliot Page"],
    duration: "2h 28m",
  },
  {
    id: 7,
    title: "Fight Club",
    year: 1999,
    genre: ["Drama"],
    director: "David Fincher",
    rating: 8.8,
    actors: ["Brad Pitt", "Edward Norton", "Helena Bonham Carter"],
    duration: "2h 19m",
  },
  {
    id: 8,
    title: "The Matrix",
    year: 1999,
    genre: ["Action", "Sci-Fi"],
    director: "Lana Wachowski, Lilly Wachowski",
    rating: 8.7,
    actors: ["Keanu Reeves", "Laurence Fishburne", "Carrie-Anne Moss"],
    duration: "2h 16m",
  },
  {
    id: 9,
    title: "Interstellar",
    year: 2014,
    genre: ["Adventure", "Drama", "Sci-Fi"],
    director: "Christopher Nolan",
    rating: 8.7,
    actors: ["Matthew McConaughey", "Anne Hathaway", "Jessica Chastain"],
    duration: "2h 49m",
  },
  {
    id: 10,
    title: "The Lord of the Rings: The Return of the King",
    year: 2003,
    genre: ["Action", "Adventure", "Drama"],
    director: "Peter Jackson",
    rating: 9.0,
    actors: ["Elijah Wood", "Viggo Mortensen", "Ian McKellen"],
    duration: "3h 21m",
  }
];

export default MoviesData;
